name: "Build Release"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "build/libs/examplemod-${{ steps.build.outputs.version }}.jar"
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency"
          game_versions: "Minecraft 1.18:1.18.1,Java 17,Fabric"
          project_id: "1123952"
          token: "${{ secrets.CF_API_TOKEN }}"